mission_handler:
  main_timer_rate: 100.0 # [Hz]
  feedback_timer_rate: 1.0 # [Hz]
  subtask_executors:
    wait:
      address: "iroc_mission_handler/WaitSubtaskExecutor"
      timer_rate: 10.0 # [Hz]
    gimbal:
      address: "iroc_mission_handler/GimbalSubtaskExecutor"
